server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:shortener;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
